# Generated by Django 3.0.3 on 2020-02-14 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('local_de_nascimento', models.DateField()),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais '), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2)),
                ('celular', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('escola', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('periodo', models.CharField(choices=[('MANHA', 'MANHA'), ('TARDE', 'TARDE'), ('NOITE', 'NOITE')], max_length=20)),
                ('pai', models.CharField(max_length=50)),
                ('profissao_pai', models.CharField(max_length=50)),
                ('mae', models.CharField(max_length=50)),
                ('profissao_mae', models.CharField(max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO'), ('SEPARADO', 'SEPARADO'), ('DIVORCIADO', 'DIVORCIADO'), ('VIUVO', 'VIUVO')], max_length=20)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('movimento_pastoral', models.CharField(max_length=50)),
                ('batizado', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=20)),
                ('data_batizado', models.DateField()),
                ('eucaristia', models.CharField(choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=20)),
                ('cidade_eucaristia', models.CharField(max_length=50)),
                ('paroquia', models.CharField(max_length=50)),
                ('diocese', models.CharField(max_length=50)),
            ],
        ),
    ]
