# Generated by Django 3.0.3 on 2020-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='historico',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='profissao_mae',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='profissao_pai',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
