# Generated by Django 3.0.3 on 2020-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20200214_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='historico',
            field=models.TextField(blank=True, help_text='Ano - Curso - Idade - Catequista - Frequência - Aproveitamento', max_length=500, null=True),
        ),
    ]
