# Generated by Django 3.0.3 on 2020-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20200214_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='local_de_nascimento',
            field=models.CharField(max_length=50),
        ),
    ]
