# Generated by Django 3.0.3 on 2020-02-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0001_initial'),
        ('cadastro', '0004_auto_20200214_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='turma.Turma'),
        ),
    ]
